name: 'Build and Test'
run-name: 'Build and Test'

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'src/**'
  push:
    tags-ignore:
      - '*'
    paths:
      - 'src/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: 'Checkout'
        uses: actions/checkout@v5
      -
        name: 'Build Test Image and Run Tests'
        run: ./build-and-test.sh --pihole_target_tag 'latest'
